{
 "title": "Chaos Dashboard",
 "time": { "from": "2023-07-12T21:07:22.257Z", "to": "2023-07-12T21:24:55.813Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(process_start_time_seconds{deployment!=\"\"}, namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(process_start_time_seconds{namespace=\"$namespace\"}, deployment)"
   },
   {
    "name": "inbound",
    "query": "label_values(request_total{dst_namespace=\"$namespace\", dst_deployment=\"$deployment\"}, deployment)"
   },
   {
    "name": "outbound",
    "query": "label_values(request_total{namespace=\"$namespace\", deployment=\"$deployment\"}, dst_deployment)"
   },
   {
    "name": "rt_route",
    "label": "Route",
    "query": {
     "query": "label_values(route_request_total{namespace=\"$namespace\"},rt_route)"
    }
   },
   {
    "name": "accepted_response_time",
    "label": "Accepted Response Time",
    "query": {
     "query": "label_values(route_response_latency_ms_bucket,le)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Failure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data for correlation coefficient calculation",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"outbound\", le=\"2000\", rt_route=\"$rt_route\", deployment=\"loadgenerator\"}[$__rate_interval])) by (rt_route)",
     "legendFormat": "{{rt_route}} (SRinT)"
    },
    {
     "expr": "(sum(rate(route_response_total{namespace=\"$namespace\", direction=\"outbound\", rt_route=\"$rt_route\", deployment=\"loadgenerator\"}[$__rate_interval]))by (rt_route) > 0 ) ",
     "legendFormat": "{{rt_route}} (SR)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "litmuschaos_experiment_start_time{chaosresult_namespace=\"litmus\"}*1000",
     "legendFormat": "{{chaosresult_name}}"
    },
    {
     "expr": "litmuschaos_experiment_chaos_injected_time{chaosresult_namespace=\"litmus\"}*1000",
     "legendFormat": "{{chaosresult_name}}"
    },
    {
     "expr": "litmuschaos_experiment_end_time{chaosresult_namespace=\"litmus\"}*1000",
     "legendFormat": "{{chaosresult_name}}"
    },
    {
     "expr": "litmuschaos_experiment_total_duration{chaosresult_namespace=\"litmus\"}",
     "legendFormat": "{{chaosresult_name}}"
    },
    {
     "expr": "litmuschaos_experiment_verdict{chaosresult_namespace=\"litmus\"}*1000",
     "legendFormat": "{{chaosresult_name}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Deployment Down",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\"}",
     "legendFormat": "{{deployment}} {{statefulset}}"
    }
   ]
  },
  {
   "title": "Ratio of Requests within Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"outbound\", rt_route=\"$rt_route\", le=\"$accepted_response_time\"}[2m])) /\r\n(sum(rate(route_response_total{namespace=\"$namespace\", direction=\"outbound\", rt_route=\"$rt_route\"}[2m]))>0)",
     "legendFormat": "Response Within Response Time"
    }
   ]
  },
  {
   "title": "Direction Outbound",
   "type": "candlestick",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.0001, sum(irate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"outbound\", rt_route=\"$rt_route\"}[$__rate_interval])) by (le, rt_route))\r\n",
     "legendFormat": "Min"
    },
    {
     "expr": "histogram_quantile(0.25, sum(irate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"outbound\", rt_route=\"$rt_route\"}[$__rate_interval])) by (le, rt_route))\r\n",
     "legendFormat": "Q1"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"outbound\", rt_route=\"$rt_route\"}[$__rate_interval])) by (le, rt_route))\r\n",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.75, sum(irate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"outbound\", rt_route=\"$rt_route\"}[$__rate_interval])) by (le, rt_route))\r\n",
     "legendFormat": "Q3"
    },
    {
     "expr": "histogram_quantile(1, sum(irate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"outbound\", rt_route=\"$rt_route\"}[$__rate_interval])) by (le, rt_route))\r\n",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(rate(route_request_total{namespace=\"$namespace\", direction=\"outbound\", rt_route=\"$rt_route\"}[$__rate_interval])) by (le, rt_route)",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "Individual SLOs",
   "type": "gauge",
   "description": "Calculates the ratio between the requests within responste time and the overall amount of requests",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", le=\"20\", rt_route=\"GET /login\"}[$__rate_interval]))\r\n/\r\n(sum(rate(route_response_total{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"GET /login\"}[$__rate_interval]))> 0 ) )",
     "legendFormat": "GET /login 20ms"
    },
    {
     "expr": "(sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", le=\"20\", rt_route=\"GET /signup\"}[$__rate_interval]))\r\n/\r\n(sum(rate(route_response_total{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"GET /signup\"}[$__rate_interval]))> 0 ) )",
     "legendFormat": "GET /signup 20ms"
    },
    {
     "expr": "(sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", le=\"20\", rt_route=\"POST /logout\"}[$__rate_interval]))\r\n/\r\n(sum(rate(route_response_total{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"POST /logout\"}[$__rate_interval]))> 0 ) )",
     "legendFormat": "POST /logout 20ms"
    },
    {
     "expr": "(sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", le=\"30\", rt_route=\"GET /\"}[$__rate_interval]))\r\n/\r\n(sum(rate(route_response_total{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"GET /\"}[$__rate_interval]))> 0 ) )",
     "legendFormat": "GET / 30ms"
    },
    {
     "expr": "(sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", le=\"30\", rt_route=\"GET /home\"}[$__rate_interval]))\r\n/\r\n(sum(rate(route_response_total{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"GET /home\"}[$__rate_interval]))> 0 ) )",
     "legendFormat": "GET /home 30ms"
    },
    {
     "expr": "(sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", le=\"300\", rt_route=\"POST /deposit\"}[$__rate_interval]))\r\n/\r\n(sum(rate(route_response_total{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"POST /deposit\"}[$__rate_interval]))> 0 ) )",
     "legendFormat": "POST /deposit 300ms"
    },
    {
     "expr": "(sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", le=\"300\", rt_route=\"POST /payment\"}[$__rate_interval]))\r\n/\r\n(sum(rate(route_response_total{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"POST /payment\"}[$__rate_interval]))> 0 ) )",
     "legendFormat": "POST /payment 300ms"
    },
    {
     "expr": "(sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", le=\"2000\", rt_route=\"POST /login\"}[$__rate_interval]))\r\n/\r\n(sum(rate(route_response_total{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"POST /login\"}[$__rate_interval]))> 0 ) )",
     "legendFormat": "POST /login 2000ms"
    },
    {
     "expr": "(sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", le=\"3000\", rt_route=\"POST /signup\"}[$__rate_interval]))\r\n/\r\n(sum(rate(route_response_total{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"POST /signup\"}[$__rate_interval]))> 0 ) )",
     "legendFormat": "POST /signup 3000ms"
    }
   ]
  },
  { "title": "Linkerd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://linkerd.io/images/identity/favicon/linkerd-favicon.png\" style=\"height:32px;\"/>&nbsp;\n  <span style=\"font-size: 32px\">deploy/$deployment</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 44 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>OUTBOUND TRAFFIC</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "OUTBOUND DEPLOYMENTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}) by (namespace, dst_deployment))"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(route_response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (rt_route) / sum(irate(route_response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (rt_route)",
     "legendFormat": "{{rt_route}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(irate(route_request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (rt_route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\", rt_route!=\"\"}[$__rate_interval])) by (le, rt_route))",
     "legendFormat": "P95 {{rt_route}}"
    }
   ]
  },
  {
   "title": "Correlation coefficient Requests Within Responste Time",
   "type": "gauge",
   "description": "Calculates the correlation coefficient between the requests within responste time and the overall amount of requests",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"outbound\", le=\"$accepted_response_time\"}[$__range])) by (rt_route)\r\n/\r\nsum(rate(route_response_total{namespace=\"$namespace\", direction=\"outbound\"}[$__range])) by (rt_route)) )\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Percentage of Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(route_response_total{namespace=\"$namespace\", direction=\"outbound\", classification=\"success\", deployment=\"loadgenerator\"}[$__range])) by (rt_route)\r\n/\r\nsum(rate(route_response_total{namespace=\"$namespace\", direction=\"outbound\", deployment=\"loadgenerator\"}[$__range])) by (rt_route)\r\n",
     "legendFormat": "{{rt_route}} {{status_code}}"
    }
   ]
  },
  {
   "title": "P01 LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.01, sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\", rt_route!=\"\"}[$__rate_interval])) by (le, rt_route))",
     "legendFormat": "P95 {{rt_route}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 73 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>Inbound TRAFFIC</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s]))"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[30s]))"
    }
   ]
  },
  {
   "title": "INBOUND DEPLOYMENTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}) by (namespace, src_deployment))"
    }
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(route_response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (rt_route) / sum(irate(route_response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (rt_route)",
     "legendFormat": "{{rt_route}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(irate(route_request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (rt_route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", rt_route!=\"\"}[$__rate_interval])) by (le, rt_route))",
     "legendFormat": "P95 {{rt_route}}"
    }
   ]
  },
  {
   "title": "P01 LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.01, sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", rt_route!=\"\"}[$__rate_interval])) by (le, rt_route))",
     "legendFormat": "P95 {{rt_route}}"
    }
   ]
  },
  {
   "title": "Inbound Latency",
   "type": "candlestick",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 93 },
   "repeat": "rt_route",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.0001, sum(irate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"$rt_route\"}[$__rate_interval])) by (le, rt_route))\r\n",
     "legendFormat": "Min"
    },
    {
     "expr": "histogram_quantile(0.25, sum(irate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"$rt_route\"}[$__rate_interval])) by (le, rt_route))\r\n",
     "legendFormat": "Q1"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"$rt_route\"}[$__rate_interval])) by (le, rt_route))\r\n",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.75, sum(irate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"$rt_route\"}[$__rate_interval])) by (le, rt_route))\r\n",
     "legendFormat": "Q3"
    },
    {
     "expr": "histogram_quantile(1, sum(irate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"$rt_route\"}[$__rate_interval])) by (le, rt_route))\r\n",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(rate(route_request_total{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"$rt_route\"}[$__rate_interval])) by (le, rt_route)",
     "legendFormat": "Volume"
    }
   ]
  },
  {
   "title": "Correlation coefficient Requests Within Responste Time",
   "type": "gauge",
   "description": "Calculates the correlation coefficient between the requests within responste time and the overall amount of requests",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7177 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", le=\"$accepted_response_time\"}[$__range])) by (rt_route)\r\n/\r\nsum(rate(route_response_total{namespace=\"$namespace\", direction=\"inbound\"}[$__range])) by (rt_route)) )\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ratio of Requests within Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 7186 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(route_response_latency_ms_bucket{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"$rt_route\", le=\"$accepted_response_time\"}[5m])) /\r\n(sum(rate(route_response_total{namespace=\"$namespace\", direction=\"inbound\", rt_route=\"$rt_route\"}[5m]))>0)",
     "legendFormat": "Response Within Response Time"
    }
   ]
  },
  {
   "title": "Outbound TCP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7194 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\",errno!=\"\"}",
       "legendFormat": "{{peer}} {{errno}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTIONS OPEN",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 80 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 80 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}"
      }
     ]
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7195 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7196 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>OUTBOUND DEPLOYMENTS</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "deploy/$outbound",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7198 },
   "repeat": "outbound",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 93 },
     "options": {
      "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://linkerd.io/images/identity/favicon/linkerd-favicon.png\" style=\"baseline; height:30px;\"/>&nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$outbound</span>\n</div>"
     }
    },
    {
     "title": "SUCCESS RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 95 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\"}[$__rate_interval])) by (dst_deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\"}[$__rate_interval])) by (dst_deployment)",
       "legendFormat": "deploy/{{dst_deployment}}"
      }
     ]
    },
    {
     "title": "REQUEST RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 95 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\", tls=\"true\"}[$__rate_interval])) by (dst_deployment)",
       "legendFormat": "🔒deploy/{{dst_deployment}}"
      },
      {
       "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\", tls!=\"true\"}[$__rate_interval])) by (dst_deployment)",
       "legendFormat": "deploy/{{dst_deployment}}"
      }
     ]
    },
    {
     "title": "LATENCY",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 95 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_deployment))",
       "legendFormat": "P50 deploy/{{dst_deployment}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_deployment))",
       "legendFormat": "P95 deploy/{{dst_deployment}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_deployment))",
       "legendFormat": "P99 deploy/{{dst_deployment}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 102 },
     "options": {
      "content": "<div>\n  <div style=\"position: absolute; top: 0, left: 0\">\n    <a href=\"https://linkerd.io\" target=\"_blank\"><img src=\"https://linkerd.io/images/identity/svg/linkerd_primary_color_white.svg\" style=\"height: 30px;\"></a>\n  </div>\n  <div id=\"version\" style=\"position: absolute; top: 0; right: 0; font-size: 15px\">\n  </div>\n</div>\n<div style=\"display:none\">\n<script type=\"text/javascript\">\nvar localReqURL =\n  window.location.href.substring(\n    0,\n    window.location.href.indexOf(\n    \"/grafana/\"\n    )\n  )+'/overview';\n\nfetch(localReqURL, {\n  credentials: 'include',\n  headers: {\n    \"Content-Type\": \"text/html; charset=utf-8\",\n  },\n})\n.then(response => response.text())\n.then(text => (new window.DOMParser()).parseFromString(text, \"text/html\"))\n.then(html => {\n  var main = html.getElementById('main');\n  var localVersion = main.getAttribute(\"data-release-version\");\n  var versionElem = document.getElementById('version');\n\n  var channel;\n  var parts = localVersion.split(\"-\", 2);\n  if (parts.length === 2) {\n    channel = parts[0];\n    versionElem.innerHTML += 'Running Linkerd ' + parts[1] + ' (' + parts[0] + ')' + '.<br>';\n  } else {\n    versionElem.innerHTML += 'Running Linkerd ' + localVersion + '.<br>';\n  }\n  var uuid = main.getAttribute(\"data-uuid\");\n\n  fetch('https://versioncheck.linkerd.io/version.json?version='+localVersion+'&uuid='+uuid+'&source=grafana', {\n    credentials: 'include',\n    headers: {\n      \"Content-Type\": \"application/json; charset=utf-8\",\n    },\n  })\n  .then(response => response.json())\n  .then(json => {\n    if (!channel || !json[channel]) {\n      versionElem.innerHTML += 'Version check failed.'\n    } else if (json[channel] === localVersion) {\n      versionElem.innerHTML += 'Linkerd is up to date.';\n    } else {\n      parts = json[channel].split(\"-\", 2);\n      if (parts.length === 2) {\n        versionElem.innerHTML += \"A new \"+parts[0]+\" version (\"+parts[1]+\") is available.\"\n      } else {\n        versionElem.innerHTML += \"A new version (\"+json[channel]+\") is available.\"\n      }\n      versionElem.innerHTML += \" <a href='https://versioncheck.linkerd.io/update' target='_blank'>Update now</a>.\";\n    }\n  });\n});\n</script>\n</div>"
     },
     "targets": [
      {}
     ]
    }
   ]
  }
 ]
}