apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: custom-1688580330
  namespace: litmus
spec:
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
    - name: custom-chaos
      steps:
        - - name: install-chaos-experiments
            template: install-chaos-experiments
        - - name: pod-delete-t1u
            template: pod-delete-t1u
        - - name: pod-delete-lnj
            template: pod-delete-lnj
    - name: install-chaos-experiments
      inputs:
        artifacts:
          - name: pod-delete-t1u
            path: /tmp/pod-delete-t1u.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                description:
                  message: |
                    Deletes a pod belonging to a deployment/statefulset/daemonset
                kind: ChaosExperiment

                metadata:
                  name: pod-delete
                  labels:
                    name: pod-delete
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 2.14.0
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - apps
                        resources:
                          - deployments
                          - statefulsets
                          - replicasets
                          - daemonsets
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - apps.openshift.io
                        resources:
                          - deploymentconfigs
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - ""
                        resources:
                          - replicationcontrollers
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - argoproj.io
                        resources:
                          - rollouts
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                    image: litmuschaos/go-runner:2.14.0
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name pod-delete
                    command:
                      - /bin/bash
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "15"
                      - name: RAMP_TIME
                        value: ""
                      - name: FORCE
                        value: "true"
                      - name: CHAOS_INTERVAL
                        value: "5"
                      - name: PODS_AFFECTED_PERC
                        value: ""
                      - name: LIB
                        value: litmus
                      - name: TARGET_PODS
                        value: ""
                      - name: NODE_LABEL
                        value: ""
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: pod-delete
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: 2.14.0
          - name: pod-delete-lnj
            path: /tmp/pod-delete-lnj.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                description:
                  message: |
                    Deletes a pod belonging to a deployment/statefulset/daemonset
                kind: ChaosExperiment

                metadata:
                  name: pod-delete
                  labels:
                    name: pod-delete
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: 2.14.0
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - apps
                        resources:
                          - deployments
                          - statefulsets
                          - replicasets
                          - daemonsets
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - apps.openshift.io
                        resources:
                          - deploymentconfigs
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - ""
                        resources:
                          - replicationcontrollers
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - argoproj.io
                        resources:
                          - rollouts
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                    image: litmuschaos/go-runner:2.14.0
                    imagePullPolicy: Always
                    args:
                      - -c
                      - ./experiments -name pod-delete
                    command:
                      - /bin/bash
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "15"
                      - name: RAMP_TIME
                        value: ""
                      - name: FORCE
                        value: "true"
                      - name: CHAOS_INTERVAL
                        value: "5"
                      - name: PODS_AFFECTED_PERC
                        value: ""
                      - name: LIB
                        value: litmus
                      - name: TARGET_PODS
                        value: ""
                      - name: NODE_LABEL
                        value: ""
                      - name: SEQUENCE
                        value: parallel
                    labels:
                      name: pod-delete
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/version: 2.14.0
      container:
        args:
          - kubectl apply -f /tmp/pod-delete-lnj.yaml -n
            {{workflow.parameters.adminModeNamespace}} &&  sleep 30
        command:
          - sh
          - -c
        image: litmuschaos/k8s:2.14.0
    - name: pod-delete-t1u
      inputs:
        artifacts:
          - name: pod-delete-t1u
            path: /tmp/chaosengine-pod-delete-t1u.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                kind: ChaosEngine

                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: pod-delete-t1u
                  labels:
                    workflow_run_id: "{{workflow.uid}}"
                spec:
                  appinfo:
                    appns: bank
                    applabel: app=frontend
                    appkind: deployment
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-delete
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "60"
                            - name: CHAOS_INTERVAL
                              value: "10"
                            - name: FORCE
                              value: "true"
                            - name: PODS_AFFECTED_PERC
                              value: "50"
                            - name: RAMP_TIME
                              value: "30"
                        probe:
                          - name: Increase-Users
                            type: httpProbe
                            mode: OnChaos
                            runProperties:
                              probeTimeout: 50
                              retry: 0
                              interval: 0
                              probePollingInterval: 10
                              initialDelaySeconds: 0
                              stopOnFailure: true
                            httpProbe/inputs:
                              url: http://loadgenerator.bank.svc.cluster.local:8080/swarm
                              insecureSkipVerify: true
                              method:
                                post:
                                  criteria: ==
                                  responseCode: "200"
                                  body: user_count=15&spawn_rate=2
                                  contentType: application/x-www-form-urlencoded
      container:
        args:
          - -file=/tmp/chaosengine-pod-delete-t1u.yaml
          - -saveName=/tmp/engine-name
        image: litmuschaos/litmus-checker:2.14.0
    - name: pod-delete-lnj
      inputs:
        artifacts:
          - name: pod-delete-lnj
            path: /tmp/chaosengine-pod-delete-lnj.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                kind: ChaosEngine

                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  generateName: pod-delete-lnj
                  labels:
                    workflow_run_id: "{{workflow.uid}}"
                spec:
                  appinfo:
                    appns: bank
                    applabel: app=userservice
                    appkind: deployment
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-delete
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "60"
                            - name: CHAOS_INTERVAL
                              value: "20"
                            - name: FORCE
                              value: "false"
                            - name: PODS_AFFECTED_PERC
                              value: "50"
                            - name: RAMP_TIME
                              value: "60"
                        probe:
                          - name: Get frontend
                            type: httpProbe
                            mode: Continuous
                            runProperties:
                              probeTimeout: 40
                              retry: 3
                              interval: 1
                              probePollingInterval: 1
                              initialDelaySeconds: 1
                              stopOnFailure: false
                            httpProbe/inputs:
                              url: http://frontend.bank.svc.cluster.local:80/home
                              insecureSkipVerify: true
                              method:
                                get:
                                  criteria: ==
                                  responseCode: "200"
                          - name: Login
                            type: httpProbe
                            mode: Continuous
                            runProperties:
                              probeTimeout: 1000
                              retry: 3
                              interval: 1
                              stopOnFailure: false
                            httpProbe/inputs:
                              method:
                                post:
                                  criteria: ==
                                  responseCode: "200"
                                  body: username=testuser&password=password
                                  contentType: application/x-www-form-urlencoded
                              url: http://frontend.bank.svc.cluster.local:80/login
                          - name: Decrease-Users
                            type: httpProbe
                            mode: EOT
                            runProperties:
                              probeTimeout: 50
                              retry: 0
                              interval: 0
                              probePollingInterval: 10
                              initialDelaySeconds: 0
                              stopOnFailure: true
                            httpProbe/inputs:
                              url: http://loadgenerator.bank.svc.cluster.local:8080/swarm
                              insecureSkipVerify: true
                              method:
                                post:
                                  criteria: ==
                                  responseCode: "200"
                                  body: user_count=5&spawn_rate=1
                                  contentType: application/x-www-form-urlencoded                               
      container:
        args:
          - -file=/tmp/chaosengine-pod-delete-lnj.yaml
          - -saveName=/tmp/engine-name
        image: litmuschaos/litmus-checker:2.14.0
