{
 "title": "Resource Utilization Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[$__rate_interval]) ) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage over last 30min",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(deployment) (rate(label_replace(container_cpu_usage_seconds_total{container!=\"POD\", pod!=\"\", namespace=\"$namespace\"}, \"deployment\", \"$1\", \"pod\", \"([^\\\\-]+).*\")[30m :]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(deployment) (rate(label_replace(container_memory_usage_bytes{container!=\"POD\", pod!=\"\", namespace=\"$namespace\"}, \"deployment\", \"$1\", \"pod\", \"([^\\\\-]+).*\")[30m :]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Litmus Chaos Chaos durations interleaved with Node Exporter & Kube-State Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Chaos - Node - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate1m",
     "legendFormat": "\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Chaos - Node - Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio",
     "legendFormat": "\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Chaos - Pod - CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{container!=\"POD\", pod!=\"\", namespace=\"$namespace\"}[5m]))",
     "legendFormat": "\"{{pod}}\""
    }
   ]
  },
  {
   "title": "Chaos - Pod - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"POD\",pod!=\"\",namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "\"{{pod}}\""
    }
   ]
  }
 ]
}