apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-pod
spec:
  selector:
    matchLabels:
      app: debug-pod
  template:
    metadata:
      labels:
        app: debug-pod
    spec:
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: debug-pod
          image: centos:latest
          command: ["/bin/sh"]
          args: ["-ec", "while :; do echo .; sleep 5;done"]
          volumeMounts:
            - name: datadir
              mountPath: "/bitnami/mongodb"
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: litmus-mongodb
