kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: podtato-ns-podtato-1679578913
  namespace: litmus
  creationTimestamp: null
  labels:
    cluster_id: 934286c9-b729-4581-92a3-b75e5a29b62f
    subject: podtato-ns-podtato_litmus
    workflow_id: cba675e1-3f69-4a0b-9bd0-f72f876a2ad3
    workflows.argoproj.io/controller-instanceid: 934286c9-b729-4581-92a3-b75e5a29b62f
spec:
  templates:
    - name: argowf-chaos
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: install-application
            template: install-application
            arguments: {}
        - - name: install-chaos-experiments
            template: install-chaos-experiments
            arguments: {}
        - - name: pod-delete
            template: pod-delete
            arguments: {}
        - - name: revert-chaos
            template: revert-chaos
            arguments: {}
          - name: delete-application
            template: delete-application
            arguments: {}
    - name: install-application
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/litmus-app-deployer:latest
        args:
          - -namespace=podtato
          - -typeName=resilient
          - -operation=apply
          - -timeout=400
          - -app=podtato-head
          - -scope=namespace
        resources: {}
    - name: install-chaos-experiments
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:latest
        command:
          - sh
          - -c
        args:
          - kubectl apply -f
            https://hub.litmuschaos.io/api/chaos/2.14.0?file=charts/generic/experiments.yaml
            -n {{workflow.parameters.adminModeNamespace}} ; sleep 30
        resources: {}
    - name: pod-delete
      inputs:
        artifacts:
          - name: pod-delete
            path: /tmp/chaosengine.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                kind: ChaosEngine

                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    workflow_run_id: "{{workflow.uid}}"
                  generateName: podtato-main-pod-delete-chaos
                spec:
                  appinfo:
                    appns: "podtato"
                    applabel: name=podtato-main
                    appkind: deployment
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  jobCleanUpPolicy: retain
                  components:
                    runner:
                      imagePullPolicy: Always
                  experiments:
                    - name: pod-delete
                      spec:
                        probe:
                          - name: check-podtato-main-access-url
                            type: httpProbe
                            httpProbe/inputs:
                              url: http://podtato-main.podtato.svc.cluster.local:9000
                              insecureSkipVerify: false
                              method:
                                get:
                                  criteria: ==
                                  responseCode: "200"
                            mode: Continuous
                            runProperties:
                              probeTimeout: 100
                              interval: 1
                              retry: 1
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "30"
                            - name: CHAOS_INTERVAL
                              value: "10"
                            - name: FORCE
                              value: "false"
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: litmuschaos/litmus-checker:latest
        args:
          - -file=/tmp/chaosengine.yaml
          - -saveName=/tmp/engine-name
        resources: {}
    - name: delete-application
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/litmus-app-deployer:latest
        args:
          - -namespace=podtato
          - -typeName=resilient
          - -operation=delete
          - -app=podtato-head
        resources: {}
    - name: revert-chaos
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:latest
        command:
          - sh
          - -c
        args:
          - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n
            {{workflow.parameters.adminModeNamespace}}
        resources: {}
  entrypoint: argowf-chaos
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
  serviceAccountName: argo-chaos
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
status:
  ? startedAt
  ? finishedAt
